# Nombre del flujo de trabajo
name: Sincronización Diaria de Datos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias de Node.js
        run: npm install --legacy-peer-deps

      - name: Crear .env para el servicio de persistencia
        run: |
          echo "PORT=3003" >> ./services/persistence-api/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./services/persistence-api/.env
      
      - name: Crear .env para el servicio de ingesta de rendimiento
        run: |
          echo "PORT=3002" >> ./services/ingestor-grafana-rendimiento/.env
          echo "GRAFANA_DOWNLOAD_URL=${{ secrets.GRAFANA_DOWNLOAD_URL }}" >> ./services/ingestor-grafana-rendimiento/.env
          echo "PERSISTENCE_API_URL=http://localhost:3003" >> ./services/ingestor-grafana-rendimiento/.env

      - name: Crear .env para el servicio de ingesta de Jira
        run: |
          echo "JIRA_EMAIL=${{ secrets.JIRA_EMAIL }}" >> ./services/ingestor-jira/.env
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> ./services/ingestor-jira/.env
          echo "FILTER_IDS=${{ secrets.JIRA_FILTER_IDS }}" >> ./services/ingestor-jira/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./services/ingestor-jira/.env
          echo "PERSISTENCE_API_URL=http://localhost:3003" >> ./services/ingestor-jira/.env

      # --- NUEVO PASO DE DIAGNÓSTICO ---
      # Este paso imprimirá el contenido del script para que podamos verlo.
      - name: Mostrar contenido del script orquestador
        run: cat ./automation/run-sync.js

      # 5. Ejecutar el script orquestador
      - name: Ejecutar el script de sincronización
        run: node ./automation/run-sync.js