# Nombre del flujo de trabajo
name: Sincronización Diaria de Jira

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Se ejecuta todos los días a las 8:00 AM UTC

jobs:
  sync-jira-data:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias de Node.js
        run: npm install

      - name: Ejecutar el script de sincronización de Jira
        # La ruta al script que orquesta la ejecución
        run: node ./automation/run-sync.js 
        env:
          # --- Secretos para PostgreSQL ---
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          
          # --- Secretos para Jira ---
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          JIRA_FILTERS: ${{ secrets.JIRA_FILTERS }}