# Nombre del flujo de trabajo
name: Sincronización Diaria de Datos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  sync-data:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias de Node.js
        run: npm install --legacy-peer-deps

      # --- CAMBIO IMPORTANTE ---
      # Ya no creamos archivos .env. Inyectamos los secretos directamente.
      - name: Ejecutar el script de sincronización
        run: node ./automation/run-sync.js
        env:
          # Aquí se inyectan tus secretos de forma segura como variables de entorno
          # para que process.env las pueda leer directamente en todos los scripts.
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          JIRA_FILTER_IDS: ${{ secrets.JIRA_FILTER_IDS }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GRAFANA_DOWNLOAD_URL: ${{ secrets.GRAFANA_DOWNLOAD_URL }}
          WINDOWS_USER: ${{ secrets.WINDOWS_USER }}
          WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}
          GRAFANA_API_URL: ${{ secrets.GRAFANA_API_URL }}
          GRAFANA_DATASOURCE_ID: ${{ secrets.GRAFANA_DATASOURCE_ID }}
          GRAFANA_ORG_ID: ${{ secrets.GRAFANA_ORG_ID }}
          GRAFANA_MASIVOS_API_URL: ${{ secrets.GRAFANA_MASIVOS_API_URL }}
          GRAFANA_MASIVOS_DATASOURCE_ID: ${{ secrets.GRAFANA_MASIVOS_DATASOURCE_ID }}
          GRAFANA_MASIVOS_ORG_ID: ${{ secrets.GRAFANA_MASIVOS_ORG_ID }}