# Nombre del flujo de trabajo
name: Sincronización Diaria de Datos

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta todos los días a las 13:00 PM UTC (10:00 AM de Argentina)
    - cron: '0 13 * * *'

jobs:
  sync-data:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias de Node.js
        run: npm install

      - name: Ejecutar el script de sincronización
        run: node ./automation/run-sync.js 
        env:
          # --- Secretos para PostgreSQL (compartidos) ---
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          
          # --- Secretos para Jira ---
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          JIRA_FILTERS: ${{ secrets.JIRA_FILTERS }}

          # --- Secretos para Grafana (Individuos) ---
          GRAFANA_API_URL: ${{ secrets.GRAFANA_API_URL }}
          GRAFANA_DATASOURCE_ID: ${{ secrets.GRAFANA_DATASOURCE_ID }}
          GRAFANA_ORG_ID: ${{ secrets.GRAFANA_ORG_ID }}

          # --- ¡NUEVO! Secretos para Grafana (Masivos) ---
          GRAFANA_MASIVOS_API_URL: ${{ secrets.GRAFANA_MASIVOS_API_URL }}
          GRAFANA_MASIVOS_DATASOURCE_ID: ${{ secrets.GRAFANA_MASIVOS_DATASOURCE_ID }}
          GRAFANA_MASIVOS_ORG_ID: ${{ secrets.GRAFANA_MASIVOS_ORG_ID }}