# Nombre del flujo de trabajo
name: Sincronización Diaria de Datos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *' # 11:00 UTC (8:00 AM en Argentina)

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # --- CAMBIO 1: AÑADIDO PASO PARA INSTALAR DEPENDENCIAS ---
      # Este paso es crucial. Instala todas las librerías necesarias
      # definidas en tu package.json (axios, mongodb, node-fetch, etc.)
      - name: Instalar dependencias de Node.js
        run: npm install --legacy-peer-deps

      # --- PASO DE CREAR .env (SIN CAMBIOS PARA OTROS SERVICIOS) ---
      - name: Crear .env para el servicio de persistencia
        run: |
          echo "PORT=3003" >> ./services/persistence-api/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./services/persistence-api/.env
      
      - name: Crear .env para el servicio de ingesta de rendimiento
        run: |
          echo "PORT=3002" >> ./services/ingestor-grafana-rendimiento/.env
          echo "GRAFANA_DOWNLOAD_URL=${{ secrets.GRAFANA_DOWNLOAD_URL }}" >> ./services/ingestor-grafana-rendimiento/.env
          echo "PERSISTENCE_API_URL=http://localhost:3003" >> ./services/ingestor-grafana-rendimiento/.env

      # --- CAMBIO 2: AJUSTADO EL .env PARA EL NUEVO SCRIPT DE JIRA ---
      # Ahora creamos las variables que nuestro script api-ingestor.js necesita.
      - name: Crear .env para el servicio de ingesta de Jira
        run: |
          echo "JIRA_EMAIL=${{ secrets.JIRA_EMAIL }}" >> ./services/ingestor-jira/.env
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> ./services/ingestor-jira/.env
          echo "FILTER_IDS=${{ secrets.JIRA_FILTER_IDS }}" >> ./services/ingestor-jira/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./services/ingestor-jira/.env
          # La siguiente variable la hardcodeamos porque el script de orquestación podría necesitarla
          echo "PERSISTENCE_API_URL=http://localhost:3003" >> ./services/ingestor-jira/.env

      # --- PASO FINAL (SIN CAMBIOS) ---
      - name: Ejecutar el script de sincronización
        run: node ./automation/run-sync.js